services:
    mysql:
        container_name: "rfsim5g-mysql"
        image: mysql:8.0
        volumes:
            - ./oai_db.sql:/docker-entrypoint-initdb.d/oai_db.sql
            - ./mysql-healthcheck.sh:/tmp/mysql-healthcheck.sh
        environment:
            - TZ=Europe/Paris
            - MYSQL_DATABASE=oai_db
            - MYSQL_USER=test
            - MYSQL_PASSWORD=test
            - MYSQL_ROOT_PASSWORD=linux
        healthcheck:
            test: /bin/bash -c "/tmp/mysql-healthcheck.sh"
            interval: 10s
            timeout: 5s
            retries: 30
        networks:
            public_net:
                ipv4_address: 192.168.71.131
    oai-amf:
        container_name: "rfsim5g-oai-amf"
        image: oaisoftwarealliance/oai-amf:v2.0.0
        environment:
            - TZ=Europe/paris
        volumes:
            - ./mini_nonrf_config.yaml:/openair-amf/etc/config.yaml
        depends_on:
            - mysql
        networks:
            public_net:
                ipv4_address: 192.168.71.132
    oai-smf:
        container_name: "rfsim5g-oai-smf"
        image: oaisoftwarealliance/oai-smf:v2.0.0
        environment:
            - TZ=Europe/Paris
        volumes:
            - ./mini_nonrf_config.yaml:/openair-smf/etc/config.yaml
        depends_on:
            - oai-amf
        networks:
            public_net:
                ipv4_address: 192.168.71.133
    oai-upf:
        container_name: "rfsim5g-oai-upf"
        image: oaisoftwarealliance/oai-upf:v2.0.0
        environment:
            - TZ=Europe/Paris
        volumes:
            - ./mini_nonrf_config.yaml:/openair-upf/etc/config.yaml
        depends_on:
            - oai-smf
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        cap_drop:
            - ALL
        privileged: true
        networks:
            public_net:
                ipv4_address: 192.168.71.134
            traffic_net:
                ipv4_address: 192.168.72.134
    oai-ext-dn:
        privileged: true
        container_name: rfsim5g-oai-ext-dn
        image: oaisoftwarealliance/trf-gen-cn5g:focal
        entrypoint: /bin/bash -c \
              "iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE;"\
              "ip route add 12.1.1.0/24 via 192.168.72.134 dev eth0; sleep infinity"
        depends_on:
            - oai-upf
        networks:
            traffic_net:
                ipv4_address: 192.168.72.135
        healthcheck:
            test: /bin/bash -c "ping -c 2 192.168.72.134"
            interval: 10s
            timeout: 5s
            retries: 5
    oai-gnb:
        image: oaisoftwarealliance/oai-gnb:develop
        container_name: rfsim5g-oai-gnb
        cap_drop:
            - ALL
        environment:
            USE_ADDITIONAL_OPTIONS: --sa -E --rfsim --log_config.global_log_options level,nocolor,time
            ASAN_OPTIONS: detect_leaks=0
        depends_on:
            - oai-ext-dn
        networks:
            public_net:
                ipv4_address: 192.168.71.140
        volumes:
            - ../../conf_files/gnb.sa.band78.106prb.rfsim.conf:/opt/oai-gnb/etc/gnb.conf
        healthcheck:
            test: /bin/bash -c "pgrep nr-softmodem"
            interval: 10s
            timeout: 5s
            retries: 5


    ######################################### UE #########################################    
    oai-nr-ue-1:
        image: oai-nr-ue:latest
        container_name: rfsim5g-oai-nr-ue-1
        cap_drop:
            - ALL
        cap_add:
            - NET_ADMIN  
            - NET_RAW    
        environment:
            USE_ADDITIONAL_OPTIONS: --band 78 -E --sa --rfsim -r 106 --numerology 1 --ssb 516 -C 3319680000 --rfsimulator.serveraddr 10.64.44.47 --uicc0.imsi 208990100001101 --rfsimulator.options chanmod --telnetsrv --channelmod.modellist modellist_rfsimu_1 --channelmod.modellist_rfsimu_1.[0].ploss_dB 31.72 # 21%
        networks:
            public_net:
                ipv4_address: 192.168.71.150
        devices:
             - /dev/net/tun:/dev/net/tun
        volumes:
            - ../../../../conf/nrue.uicc.conf:/opt/oai-nr-ue/etc/nr-ue.conf
            - ../../../../results/iperf:/tmp
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5
            
    oai-nr-ue-2:
        image: oai-nr-ue:latest
        container_name: rfsim5g-oai-nr-ue-2
        cap_drop:
            - ALL
        cap_add:
            - NET_ADMIN  
            - NET_RAW    
        environment:
            USE_ADDITIONAL_OPTIONS: --band 78 -E --sa --rfsim -r 106 --numerology 1 --ssb 516 -C 3319680000 --rfsimulator.serveraddr 10.64.44.47 --uicc0.imsi 208990100001102 --rfsimulator.options chanmod --telnetsrv --channelmod.modellist modellist_rfsimu_1 --channelmod.modellist_rfsimu_1.[0].ploss_dB 31.66 # 18%
        networks:
            public_net:
                ipv4_address: 192.168.71.151
        devices:
             - /dev/net/tun:/dev/net/tun
        volumes:
            - ../../../../conf/nrue.uicc.conf:/opt/oai-nr-ue/etc/nr-ue.conf
            - ../../../../results/iperf:/tmp
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5

    oai-nr-ue-3:
        image: oai-nr-ue:latest
        container_name: rfsim5g-oai-nr-ue-3
        cap_drop:
            - ALL
        cap_add:
            - NET_ADMIN  
            - NET_RAW    
        environment:
            USE_ADDITIONAL_OPTIONS: --band 78 -E --sa --rfsim -r 106 --numerology 1 --ssb 516 -C 3319680000 --rfsimulator.serveraddr 10.64.44.47 --uicc0.imsi 208990100001103 --rfsimulator.options chanmod --telnetsrv --channelmod.modellist modellist_rfsimu_1 --channelmod.modellist_rfsimu_1.[0].ploss_dB 31.62 # 14%
        networks:
            public_net:
                ipv4_address: 192.168.71.152
        devices:
             - /dev/net/tun:/dev/net/tun
        volumes:
            - ../../../../conf/nrue.uicc.conf:/opt/oai-nr-ue/etc/nr-ue.conf
            - ../../../../results/iperf:/tmp
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5
            
    oai-nr-ue-4:
        image: oai-nr-ue:latest
        container_name: rfsim5g-oai-nr-ue-4
        cap_drop:
            - ALL
        cap_add:
            - NET_ADMIN  
            - NET_RAW    
        environment:
            USE_ADDITIONAL_OPTIONS: --band 78 -E --sa --rfsim -r 106 --numerology 1 --ssb 516 -C 3319680000 --rfsimulator.serveraddr 10.64.44.47 --uicc0.imsi 208990100001104 --rfsimulator.options chanmod --telnetsrv --channelmod.modellist modellist_rfsimu_1 --channelmod.modellist_rfsimu_1.[0].ploss_dB 23.8 # 11%
        networks:
            public_net:
                ipv4_address: 192.168.71.153
        devices:
             - /dev/net/tun:/dev/net/tun
        volumes:
            - ../../../../conf/nrue.uicc.conf:/opt/oai-nr-ue/etc/nr-ue.conf
            - ../../../../results/iperf:/tmp
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5
      
    oai-nr-ue-5:
        image: oai-nr-ue:latest
        container_name: rfsim5g-oai-nr-ue-5
        cap_drop:
            - ALL
        cap_add:
            - NET_ADMIN  
            - NET_RAW    
        environment:
            USE_ADDITIONAL_OPTIONS: --band 78 -E --sa --rfsim -r 106 --numerology 1 --ssb 516 -C 3319680000 --rfsimulator.serveraddr 10.64.44.47 --uicc0.imsi 208990100001105 --rfsimulator.options chanmod --telnetsrv --channelmod.modellist modellist_rfsimu_1 --channelmod.modellist_rfsimu_1.[0].ploss_dB 18.5 # 8%
        networks:
            public_net:
                ipv4_address: 192.168.71.154
        devices:
             - /dev/net/tun:/dev/net/tun
        volumes:
            - ../../../../conf/nrue.uicc.conf:/opt/oai-nr-ue/etc/nr-ue.conf
            - ../../../../results/iperf:/tmp
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5
            
    oai-nr-ue-6:
        image: oai-nr-ue:latest
        container_name: rfsim5g-oai-nr-ue-6
        cap_drop:
            - ALL
        cap_add:
            - NET_ADMIN  
            - NET_RAW    
        environment:
            USE_ADDITIONAL_OPTIONS: --band 78 -E --sa --rfsim -r 106 --numerology 1 --ssb 516 -C 3319680000 --rfsimulator.serveraddr 10.64.44.47 --uicc0.imsi 208990100001106 --rfsimulator.options chanmod --telnetsrv --channelmod.modellist modellist_rfsimu_1 --channelmod.modellist_rfsimu_1.[0].ploss_dB 16.4 # 4%
        networks:
            public_net:
                ipv4_address: 192.168.71.155
        devices:
             - /dev/net/tun:/dev/net/tun
        volumes:
            - ../../../../conf/nrue.uicc.conf:/opt/oai-nr-ue/etc/nr-ue.conf
            - ../../../../results/iperf:/tmp
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5

    oai-nr-ue-7:
        image: oai-nr-ue:latest
        container_name: rfsim5g-oai-nr-ue-7
        cap_drop:
            - ALL
        cap_add:
            - NET_ADMIN  
            - NET_RAW    
        environment:
            USE_ADDITIONAL_OPTIONS: --band 78 -E --sa --rfsim -r 106 --numerology 1 --ssb 516 -C 3319680000 --rfsimulator.serveraddr 10.64.44.47 --uicc0.imsi 208990100001107 --rfsimulator.options chanmod --telnetsrv --channelmod.modellist modellist_rfsimu_1 --channelmod.modellist_rfsimu_1.[0].ploss_dB 15.2 # 0.5%
        networks:
            public_net:
                ipv4_address: 192.168.71.156
        devices:
             - /dev/net/tun:/dev/net/tun
        volumes:
            - ../../../../conf/nrue.uicc.conf:/opt/oai-nr-ue/etc/nr-ue.conf
            - ../../../../results/iperf:/tmp
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5

    oai-nr-ue-8:
        image: oai-nr-ue:latest
        container_name: rfsim5g-oai-nr-ue-8
        cap_drop:
            - ALL
        cap_add:
            - NET_ADMIN  
            - NET_RAW    
        environment:
            USE_ADDITIONAL_OPTIONS: --band 78 -E --sa --rfsim -r 106 --numerology 1 --ssb 516 -C 3319680000 --rfsimulator.serveraddr 10.64.44.47 --uicc0.imsi 208990100001108 --rfsimulator.options chanmod --telnetsrv
        networks:
            public_net:
                ipv4_address: 192.168.71.157
        devices:
             - /dev/net/tun:/dev/net/tun
        volumes:
            - ../../../../conf/nrue.uicc.conf:/opt/oai-nr-ue/etc/nr-ue.conf
            - ../../../../results/iperf:/tmp
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5
            
    oai-nr-ue-9:
        image: oai-nr-ue:latest
        container_name: rfsim5g-oai-nr-ue-9
        cap_drop:
            - ALL
        cap_add:
            - NET_ADMIN  
            - NET_RAW    
        environment:
            USE_ADDITIONAL_OPTIONS: --band 78 -E --sa --rfsim -r 106 --numerology 1 --ssb 516 -C 3319680000 --rfsimulator.serveraddr 10.64.44.47 --uicc0.imsi 208990100001109 --rfsimulator.options chanmod --telnetsrv
        networks:
            public_net:
                ipv4_address: 192.168.71.158
        devices:
             - /dev/net/tun:/dev/net/tun
        volumes:
            - ../../../../conf/nrue.uicc.conf:/opt/oai-nr-ue/etc/nr-ue.conf
            - ../../../../results/iperf:/tmp
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5

    oai-nr-ue-10:
        image: oai-nr-ue:latest
        container_name: rfsim5g-oai-nr-ue-10
        cap_drop:
            - ALL
        cap_add:
            - NET_ADMIN  
            - NET_RAW    
        environment:
            USE_ADDITIONAL_OPTIONS: --band 78 -E --sa --rfsim -r 106 --numerology 1 --ssb 516 -C 3319680000 --rfsimulator.serveraddr 10.64.44.47 --uicc0.imsi 208990100001110 --rfsimulator.options chanmod --telnetsrv
        networks:
            public_net:
                ipv4_address: 192.168.71.159
        devices:
             - /dev/net/tun:/dev/net/tun
        volumes:
            - ../../../../conf/nrue.uicc.conf:/opt/oai-nr-ue/etc/nr-ue.conf
            - ../../../../results/iperf:/tmp
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5
            
    oai-nr-ue-11:
        image: oai-nr-ue:latest
        container_name: rfsim5g-oai-nr-ue-11
        cap_drop:
            - ALL
        cap_add:
            - NET_ADMIN  
            - NET_RAW    
        environment:
            USE_ADDITIONAL_OPTIONS: --band 78 -E --sa --rfsim -r 106 --numerology 1 --ssb 516 -C 3319680000 --rfsimulator.serveraddr 10.64.44.47 --uicc0.imsi 208990100001111 --rfsimulator.options chanmod --telnetsrv
        networks:
            public_net:
                ipv4_address: 192.168.71.160
        devices:
             - /dev/net/tun:/dev/net/tun
        volumes:
            - ../../../../conf/nrue.uicc.conf:/opt/oai-nr-ue/etc/nr-ue.conf
            - ../../../../results/iperf:/tmp
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5
      
    oai-nr-ue-12:
        image: oai-nr-ue:latest
        container_name: rfsim5g-oai-nr-ue-12
        cap_drop:
            - ALL
        cap_add:
            - NET_ADMIN  
            - NET_RAW    
        environment:
            USE_ADDITIONAL_OPTIONS: --band 78 -E --sa --rfsim -r 106 --numerology 1 --ssb 516 -C 3319680000 --rfsimulator.serveraddr 10.64.44.47 --uicc0.imsi 208990100001112 --rfsimulator.options chanmod --telnetsrv
        networks:
            public_net:
                ipv4_address: 192.168.71.161
        devices:
             - /dev/net/tun:/dev/net/tun
        volumes:
            - ../../../../conf/nrue.uicc.conf:/opt/oai-nr-ue/etc/nr-ue.conf
            - ../../../../results/iperf:/tmp
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5
            
    oai-nr-ue-13:
        image: oai-nr-ue:latest
        container_name: rfsim5g-oai-nr-ue-13
        cap_drop:
            - ALL
        cap_add:
            - NET_ADMIN  
            - NET_RAW    
        environment:
            USE_ADDITIONAL_OPTIONS: --band 78 -E --sa --rfsim -r 106 --numerology 1 --ssb 516 -C 3319680000 --rfsimulator.serveraddr 10.64.44.47 --uicc0.imsi 208990100001113 --rfsimulator.options chanmod --telnetsrv
        networks:
            public_net:
                ipv4_address: 192.168.71.162
        devices:
             - /dev/net/tun:/dev/net/tun
        volumes:
            - ../../../../conf/nrue.uicc.conf:/opt/oai-nr-ue/etc/nr-ue.conf
            - ../../../../results/iperf:/tmp
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5

    oai-nr-ue-14:
        image: oai-nr-ue:latest
        container_name: rfsim5g-oai-nr-ue-14
        cap_drop:
            - ALL
        cap_add:
            - NET_ADMIN  
            - NET_RAW    
        environment:
            USE_ADDITIONAL_OPTIONS: --band 78 -E --sa --rfsim -r 106 --numerology 1 --ssb 516 -C 3319680000 --rfsimulator.serveraddr 10.64.44.47 --uicc0.imsi 208990100001114 --rfsimulator.options chanmod --telnetsrv
        networks:
            public_net:
                ipv4_address: 192.168.71.163
        devices:
             - /dev/net/tun:/dev/net/tun
        volumes:
            - ../../../../conf/nrue.uicc.conf:/opt/oai-nr-ue/etc/nr-ue.conf
            - ../../../../results/iperf:/tmp
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5

    oai-nr-ue-15:
        image: oai-nr-ue:latest
        container_name: rfsim5g-oai-nr-ue-15
        cap_drop:
            - ALL
        cap_add:
            - NET_ADMIN  
            - NET_RAW    
        environment:
            USE_ADDITIONAL_OPTIONS: --band 78 -E --sa --rfsim -r 106 --numerology 1 --ssb 516 -C 3319680000 --rfsimulator.serveraddr 10.64.44.47 --uicc0.imsi 208990100001115 --rfsimulator.options chanmod --telnetsrv
        networks:
            public_net:
                ipv4_address: 192.168.71.164
        devices:
             - /dev/net/tun:/dev/net/tun
        volumes:
            - ../../../../conf/nrue.uicc.conf:/opt/oai-nr-ue/etc/nr-ue.conf
            - ../../../../results/iperf:/tmp
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5


            
    ######################################################################################    

networks:
    public_net:
        driver: bridge
        name: rfsim5g-oai-public-net
        ipam:
            config:
                - subnet: 192.168.71.128/26
        driver_opts:
            com.docker.network.bridge.name: "rfsim5g-public"
    traffic_net:
        driver: bridge
        name: rfsim5g-oai-traffic-net
        ipam:
            config:
                - subnet: 192.168.72.128/26
        driver_opts:
            com.docker.network.bridge.name: "rfsim5g-traffic"
